### ISSUE TITLE
VS2015 and multiple C4589 warnings, "Constructor of abstract class X ignores initializer for virtual base class Y"

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#214]
Using [Visual C++ 2015 stand alone toolchain](http://blogs.msdn.microsoft.com/vcblog/2015/11/02/announcing-visual-c-build-tools-2015-standalone-c-tools-for-build-environments/) and [cryptest.nmake](http://github.com/weidai11/cryptopp/blob/master/cryptest.nmake):

```
        cl.exe /nologo /W4 /D_MBCS /Zi /TP /EHsc /MD /FI sdkddkver.h /FI winapif
amily.h /c wait.cpp
wait.cpp
c:\users\jeff\desktop\cryptopp\wait.h(152): warning C4589: Constructor of abstra
ct class 'CryptoPP::WaitObjectsTracer' ignores initializer for virtual base clas
s 'CryptoPP::Tracer'
c:\users\jeff\desktop\cryptopp\wait.h(152): note: virtual base classes are only
initialized by the most-derived type
...

        cl.exe /nologo /W4 /D_MBCS /Zi /TP /EHsc /MD /FI sdkddkver.h /FI winapif
amily.h /c network.cpp
network.cpp
c:\users\jeff\desktop\cryptopp\wait.h(152): warning C4589: Constructor of abstra
ct class 'CryptoPP::WaitObjectsTracer' ignores initializer for virtual base clas
s 'CryptoPP::Tracer'
c:\users\jeff\desktop\cryptopp\wait.h(152): note: virtual base classes are only
initialized by the most-derived type
...

        cl.exe /nologo /W4 /D_MBCS /Zi /TP /EHsc /MD /FI sdkddkver.h /FI winapif
amily.h /c socketft.cpp
socketft.cpp
c:\users\jeff\desktop\cryptopp\wait.h(152): warning C4589: Constructor of abstra
ct class 'CryptoPP::WaitObjectsTracer' ignores initializer for virtual base clas
s 'CryptoPP::Tracer'
c:\users\jeff\desktop\cryptopp\wait.h(152): note: virtual base classes are only
initialized by the most-derived type
...

        cl.exe /nologo /W4 /D_MBCS /Zi /TP /EHsc /MD /FI sdkddkver.h /FI winapif
amily.h /c winpipes.cpp
winpipes.cpp
c:\users\jeff\desktop\cryptopp\wait.h(152): warning C4589: Constructor of abstra
ct class 'CryptoPP::WaitObjectsTracer' ignores initializer for virtual base clas
s 'CryptoPP::Tracer'
c:\users\jeff\desktop\cryptopp\wait.h(152): note: virtual base classes are only
initialized by the most-derived type
...

        cl.exe /nologo /W4 /D_MBCS /Zi /TP /EHsc /MD /FI sdkddkver.h /FI winapif
amily.h /c test.cpp
test.cpp
c:\users\jeff\desktop\cryptopp\wait.h(152): warning C4589: Constructor of abstra
ct class 'CryptoPP::WaitObjectsTracer' ignores initializer for virtual base clas
s 'CryptoPP::Tracer'
c:\users\jeff\desktop\cryptopp\wait.h(152): note: virtual base classes are only
initialized by the most-derived type
```

**Comment by noloader** [comment]
According to [False warning C4589: Constructor of abstract class 'Class2' ignores initializer for virtual base class 'Class1'](http://connect.microsoft.com/VisualStudio/feedback/details/1581706/false-warning-c4589-constructor-of-abstract-class-class2-ignores-initializer-for-virtual-base-class-class1):

> Thank you for reporting this issue; it will be fixed in the Update 1 release of VS2015.
>
> It's far from ideal, but besides disabling the warning or defining Derived's copy and/or move constructors as deleted, the workaround is to explicitly define copy and/or move constructors for Derived that don't initialize Base.

[Note by JW: it was not fixed in Update 1].

**Comment by noloader** [comment]
Cleared at [Commit be80fcdbba204b58](https://github.com/weidai11/cryptopp/commit/be80fcdbba204b58e96c41b624807460d9eb2d7e).

**Comment by noloader** [comment]
Cleared at [Commit be80fcdbba204b58](https://github.com/weidai11/cryptopp/commit/be80fcdbba204b58e96c41b624807460d9eb2d7e).

**Comment by vidanovic** [comment]
I do not see this fixed in VS 2015 Update 2

**Comment by PowerGamer1** [comment]
The same warning is still produced in VS2017RC. At https://connect.microsoft.com/VisualStudio/feedback/details/1570496/ the issue has been closed as fixed a long time ago. Someone who clearly understands the nature of this issue should report it to Microsoft again on https://connect.microsoft.com/VisualStudio/feedback.

**Comment by noloader** [comment]
@vidanovic, @PowerGamer1,

This came up again on the mailing list. It appears the issue is still present in VS2017. Also see []().

Does anyone know how to clear the issue once and for all?
